"""Exports the schema v2 vine goldens (07..12) as hard-coded C# vectors for the EditMode tests.

    python3 -I tools/sim/export_golden_cs.py [--check]

Writes UnityProject/Assets/_Game/Tests/EditMode/Vine/GoldenVineVectors.cs. The Unity tests have no JSON reader and
must not depend on the repository layout, so the per-tick numbers are compiled in. Re-run after
`pendulum_golden.py` changes a vector (`--check` fails if the C# file is stale).
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "UnityProject", "Assets", "_Game", "Tests", "EditMode", "Vine", "GoldenVineVectors.cs")
FILES = [
    ("Perfect07", "07_vine_perfect_release.json"),
    ("Poor08", "08_vine_poor_auto_release.json"),
    ("ClampEntry8", "09a_vine_catch_clamp_entry_8.json"),
    ("ClampEntry21", "09b_vine_catch_clamp_entry_21.json"),
    ("Chain10", "10_vine_chain_two.json"),
    ("Boost12", "12_vine_boost_entry.json"),
]
STATE = {"Carried": 0, "Falling": 1, "Landed": 2}


def arr(values):
    return "new double[] { " + ", ".join("double.NaN" if v is None else repr(float(v)) for v in values) + " }"


def iarr(values):
    return "new int[] { " + ", ".join(str(int(v)) for v in values) + " }"


def build():
    lines = []
    w = lines.append
    w("// <auto-generated> by tools/sim/export_golden_cs.py from tools/sim/golden/07..12. Do not edit. </auto-generated>")
    w("namespace JungleBooze.Tests.EditMode")
    w("{")
    w("    /// <summary>Per-tick vectors of the spec 004 goldens (schema v2, float64 reference). Tick 0 is the grab tick.</summary>")
    w("    internal static class GoldenVineVectors")
    w("    {")
    w("        public const double PositionTolerance = 1e-4;")
    w("        public const double ThetaTolerance = 5e-6;")
    w("")
    for name, fn in FILES:
        d = json.load(open(os.path.join(HERE, "golden", fn)))
        ticks = d["ticks"]
        grab = d["grab"]
        swipes = [i["tick"] for i in d["inputs"]]
        grabs, rels, grades, auto = [], [], [], []
        for r in ticks:
            for e in r["events"]:
                if e["type"] == "VineGrabbed":
                    grabs.append(r["t"])
                if e["type"] == "VineReleased":
                    rels.append(r["t"])
                    grades.append({"Perfect": 3, "Good": 2, "Poor": 1}[e["grade"]])
        land = [r["t"] for r in ticks if r["state"] == "Landed"]
        w("        public static readonly GoldenVineTrace %s = new GoldenVineTrace(" % name)
        w('            "%s",' % d["name"])
        w("            %s," % arr([v["z"] for v in d["vines"]]))
        w("            %s," % iarr([v["lane"] for v in d["vines"]]))
        w("            %s," % ("true" if d["vines"][0]["over_chasm"] else "false"))
        w("            %r, %r, %r, %r," % (float(grab["z"]), float(grab["y"]), float(grab["vIn"]), float(d["speed"]["speedMultiplier"])))
        w("            %s," % iarr(swipes))
        w("            %s," % iarr(grabs))
        w("            %s," % iarr(rels))
        w("            %s," % iarr(grades))
        w("            %d," % land[0])
        w("            %s," % iarr([STATE[r["state"]] for r in ticks]))
        w("            %s," % arr([r["x"] for r in ticks]))
        w("            %s," % arr([r["y"] for r in ticks]))
        w("            %s," % arr([r["z"] for r in ticks]))
        w("            %s," % arr([r["swing"]["theta"] if "swing" in r else None for r in ticks]))
        w("            %s);" % arr([r["swing"]["omega"] if "swing" in r else None for r in ticks]))
        w("")
    w("    }")
    w("}")
    return "\n".join(lines) + "\n"


def main():
    text = build()
    if "--check" in sys.argv:
        ok = os.path.exists(OUT) and open(OUT).read() == text
        print("up to date" if ok else "STALE")
        return 0 if ok else 1
    with open(OUT, "w") as f:
        f.write(text)
    print("wrote", os.path.normpath(OUT), len(text), "bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
